name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - run: npm install
      - run: npm run predeploy
        env:
          REACT_APP_MANAGER_API_KEY: ${{ secrets.REACT_APP_MANAGER_API_KEY }}
          REACT_APP_EMAIL_SERVICE_ID: ${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}
          REACT_APP_EMAIL_USER_ID: ${{ secrets.REACT_APP_EMAIL_USER_ID }}
          REACT_APP_EMAIL_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAIL_TEMPLATE_ID }}
          GENERATE_SOURCEMAP: false
      - run: npm run deploy
